### PR TITLE
Ability to change postfix (_u / _r) in project window.

### PR DESCRIPTION
**Pull request by grzybeek**
My ability to write good code might be bad :P
It needs further testing.

The only components that SHOULD have _r is lowr, feet, uppr and head. (Only if .ydd model contains skin, otherwise it should be _u)
Rest should have _u

### CODE REVIEW

**Comment by DurtyFree** [comment]
I am not really sure about this, maybe someone else has some opinion ? @Nicoo34 what do you say? :D

**Comment by grzybeek** [comment]
Well, yeah, it's kinda "advanced" option to give for users but in my opinion user should have ability to decide if he wants to add lowr_u instead of force on user to add _r. 
Same with all other components, why force users to add berds with _r when it should be _u? Why feet needs to have _r when model could be done without skin.

Maybe it should be option only for components that R* uses both _u and _r

**Comment by DurtyFree** [comment]
I think the problem here is that we still don't really understand when the game needs _r or _u postfix, we know its related to the tex id and its somehow related to the drawable type but I don't think we can hardcode it at all, past changes related to this were only done to make its easier & working for the general use cases

I am with you,  there should be some way for advanced users to decide this if they know better, but I also want this tool to be beginner friendly, so people don't need to know whether its _u, _r, or anything else

**Comment by Nicoo34** [comment]
Problem if you let the choice one of them for lowr will not work.

**Comment by grzybeek** [comment]
So let me explain, from what i've found all components that has _r also has skin in it's model, _u doesn't have skin.
Didn't found any other correlations

If component is _r:
propMask should be 17/19/21 (idk what it does besides of "toggling" model to work with skin)
texId should be 1 <- all _r components have texId set to 1

If component is _u:
propMask should be 1/3/5/7/9/11 and probably a lot of more, i've checked only 3 different R* .ymt's
texId should be 0 <- all _r components have texId set to 0


@Nicoo34 
Yeah, if you set _u to model that does have skin in model, changing skin tones won't work and there will be also problem with changing to different component in-game. And probably vice-versa, if you set _r to model that doesn't have skin in model it could not work (not sure about it because i'm doing all my models properly)

**Comment by DurtyFree** [comment]
Thanks @grzybeek for your input, I will have to think about how to properly add this. I would love to reach out to you on discord, if possible. (My discord is DurtyFree#3216)
I will come back to this when I have time, thx.

**Comment by sangyoo91** [comment]
As long as the metas are connected properly according to postfix, this should definately be a feature and would advance this tool by a lot. Like @DurtyFree said, we still don't understand ex
actly how rage handles / maps ids within a 100%, but what @grzybeek is pointing out is the way forward.

_u and _r postfixes not only relate to skin but also, most models (custom) work better as _u models as long as they dont have skin data.

**Comment by sangyoo91** [comment]
To add, starting with detecting user defined postfix and automatically outputting mostly used propmask/texId on build might be a good place to start so we can gather data and see what affects what and what works with what :D

**Comment by DurtyFree** [comment]
@sangyoo91 I agree, this approach could help us figuring out more. But sadly I don't have time for this project currently :/ I would be glad if somebody else would feel like implementing that :D

**Comment by sangyoo91** [comment]
@grzybeek Does this commit have the propmask and textId settings already applied?

**Comment by grzybeek** [comment]
@sangyoo91 Yes, i'll drop here compiled version so maybe more people can give a feedback, from my testing everything works fine.
[alttool.zip](https://github.com/DurtyFree/altv-cloth-tool/files/6520521/alttool.zip)


@DurtyFree Maybe you'd like to say how you see this change, I will try to do it your way in my free time

**Comment by sangyoo91** [comment]
@grzybeek I'll test the compiled version too after work tonite.

**Comment by HonzaVu** [comment]
> @sangyoo91 Yes, i'll drop here compiled version so maybe more people can give a feedback, from my testing everything works fine.
> [alttool.zip](https://github.com/DurtyFree/altv-cloth-tool/files/6520521/alttool.zip)
> 
> @DurtyFree Maybe you'd like to say how you see this change, I will try to do it your way in my free time

Hi so i indeed tried your version with every possible variation and it does work with both postfix's perfectly and the textures are working too which is great. Good job!

**Comment by DurtyFree** [comment]
> 
> 
> @sangyoo91 Yes, i'll drop here compiled version so maybe more people can give a feedback, from my testing everything works fine.
> [alttool.zip](https://github.com/DurtyFree/altv-cloth-tool/files/6520521/alttool.zip)
> 
> @DurtyFree Maybe you'd like to say how you see this change, I will try to do it your way in my free time

Sadly the PR is a bit messed up but I will try reimpliment it and release a new version so we get more peoples feedback

**Comment by sangyoo91** [comment]
@grzybeek Havent tested pants yet, but male shoes work perfectly. I'll test female too and let you know :D

**Comment by sangyoo91** [comment]
@grzybeek  Works well with female as well. One thing that existed well before this awesome update is, for females, when you equip a highheel shoe then switch to a none highheel added on shoes, the shoes are lifted up in the air as if they are high heels.

Wish I knew a way to fix or help you with this but so far Ive had no success :(

**Comment by grzybeek** [comment]
> @grzybeek Works well with female as well. One thing that existed well before this awesome update is, for females, when you equip a highheel shoe then switch to a none highheel added on shoes, the shoes are lifted up in the air as if they are high heels.
> 
> Wish I knew a way to fix or help you with this but so far Ive had no success :(

Never had such issue by myself, do you use custom _*_creaturemetadata.ymt_ for your shoes? Not sure if it is required, but I have it and never had any issues.

**Comment by sangyoo91** [comment]
@grzybeek  I'll try to get a video up soon. I do not use a creaturemetdata file for my shoes.

On a separate note, it would be nice if the json saved for alttools remembers the _u, _r postfix for each items, or at least auto selects it based on file name :D

**Comment by sangyoo91** [comment]
@grzybeek Hey! How would you like me to send a video? My discord is GG777#7777 btw if you prefer discord

**Comment by sangyoo91** [comment]
I've been using @grzybeek 's updated version for about a month rn, and apart from the save config json not loading u/r postfixes (which he mentioned to me privately he did not make yet), it works really well.

**Comment by sangyoo91** [comment]
Any chance this gets pulled?

**Comment by grzybeek** [comment]
Probably not, DurtyFree said earlier that he doesn't like how I did it, so either use my compiled version or wait for his rework :P

**Comment by DurtyFree** [comment]
I am not sure how many people want / need this. Maybe just react to this message so I can priotize whether I will add something like this or not 😄

**Comment by sangyoo91** [comment]
Personally, however its done (for me autodetection makes more sense than selection), it's a must. Auto skin color correction and more proper support for models and so on. 

If its auto detection, it should read if the model ends with `_u` or `_r`  and ouput based on what the model ends with. I would do the coding part myself if I knew how... I'm not invested in C and have been a node dev for my whole life.

Anyways, I hope it gets worked on. This is the closest and best tool so far from my experience with add-on clothes.

**Comment by DurtyFree** [comment]
This will be implemented in the next version, keep an eye on https://github.com/DurtyFree/durty-cloth-tool/releases

**Comment by grzybeek** [comment]
It would be really cool if you could at least push this one to public repository, with a download link in a readme 😛
Don't leave people that don't want to pay with broken versions of alttool, if you want me to fix saving projects to json or something, let me know. It is really not fair that I spent time to fix critical issue in your fork, and you didn't push that and released paywalled version lol...

**Comment by DurtyFree** [comment]
> It would be really cool if you could at least push this one to public repository, with a download link in a readme 😛 Don't leave people that don't want to pay with broken versions of alttool, if you want me to fix saving projects to json or something, let me know. It is really not fair that I spent time to fix critical issue in your fork, and you didn't push that and released paywalled version lol...

The new version is actually a complete rewrite and also works differently in terms of figuring out / setting the correct texid, but yes I will merge this one and update the executeable version of the last (free) released tool here. Thx for your efforts!

**Comment by sangyoo91** [comment]
I did have the opportunity to try and test the paywalled version, but I was hospitalized and didn't have the chance to. When I came back from the hospital and had the time to test it, I think the paywall kicked in.

But I'm glad this is maintained, and would love to see it in action.

**Comment by DurtyFree** [comment]
> 

Feel free to msg me regarding this

**Comment by DurtyFree** [comment]
> I did have the opportunity to try and test the paywalled version, but I was hospitalized and didn't have the chance to. When I came back from the hospital and had the time to test it, I think the paywall kicked in.
> 
> But I'm glad this is maintained, and would love to see it in action.

Feel free to msg me regarding this

**Pull request merged**
